-- CreateTable
CREATE TABLE "checklistAnuntech" (
    "id" SERIAL NOT NULL,
    "entity_id" INTEGER,
    "company_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "company_name" TEXT,
    "order_id" TEXT,
    "technical_name" TEXT,
    "order_classification" TEXT,
    "service_order_status" TEXT,
    "payment_method" TEXT,
    "payment_condition" TEXT,
    "parts_value" DOUBLE PRECISION,
    "labor_value" DOUBLE PRECISION,
    "visit_fee" DOUBLE PRECISION,
    "received_value" DOUBLE PRECISION,
    "advance_revenue" DOUBLE PRECISION,
    "revenue_deduction" DOUBLE PRECISION,
    "notes" TEXT,
    "payment_receipt" TEXT,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "technical_id" INTEGER,

    CONSTRAINT "checklistAnuntech_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "checklist_whirlpool" (
    "id" TEXT NOT NULL,
    "entity_id" INTEGER,
    "company_id" INTEGER,
    "appliance_id" TEXT,
    "sku_code" TEXT,
    "purchase_date" TEXT,
    "invoice_number" TEXT,
    "invoice_photo" TEXT,
    "engineering_version" TEXT,
    "appliance_serial_number" TEXT,
    "label_photo" TEXT,
    "consumer_id" TEXT,
    "cell_phone_number" TEXT,
    "email" TEXT,
    "responsible_type" TEXT,
    "responsible_name" TEXT,
    "responsible_doc_number" TEXT,
    "order_id" TEXT,
    "confirmed_defect" TEXT,
    "confirmed_defect2" TEXT,
    "failure_photo1" TEXT,
    "failure_photo2" TEXT,
    "failure_photo3" TEXT,
    "failure_photo4" TEXT,
    "failure_photo5" TEXT,
    "technical_report" TEXT,
    "signature" TEXT,
    "final_status_id" TEXT,
    "final_reason_id" TEXT,
    "rescheduling_date" TIMESTAMP(3),
    "rescheduling_period" TEXT,
    "parts_price" DOUBLE PRECISION,
    "labor_price" DOUBLE PRECISION,
    "visit_price" DOUBLE PRECISION,
    "displacement_price" DOUBLE PRECISION,
    "total_price" DOUBLE PRECISION,
    "received_price" DOUBLE PRECISION,
    "payment_method" TEXT,
    "notes" TEXT,
    "service_warranty" TEXT,
    "parts_warranty" TEXT,
    "approved" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "checklist_whirlpool_pkey" PRIMARY KEY ("id")
);
