import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { GlobalClassificationStatsWrapper } from "./context/os-classification-stats";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roteiro Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GlobalClassificationStatsWrapper>
            {children}
          </GlobalClassificationStatsWrapper>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
