services:
  roteiro-digital-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roteiro-digital-backend
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://workspace:C8ZVVsvzajT1rerr@postgres_db:5432/roteiro
    networks:
      - caddy-network
      - postgresql-network

networks:
  caddy-network:
    name: caddy-network
    external: true
  postgresql-network:
    name: postgresql-network
    external: true