services:
  roteiro-digital-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roteiro-digital-backend
    restart: always
    environment:
      - NODE_ENV=production
